// Builds src/data/fx.js from the ECB daily euro reference rates CSV in research/raw.
// The CSV came from the ECB Data Portal API:
//   https://data-api.ecb.europa.eu/service/data/EXR/D.USD+DKK+SEK+PLN+CZK+HUF.EUR.SP00.A?startPeriod=2025-09-25&endPeriod=2026-09-25&format=csvdata
// Run: node scripts/build-fx.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const csv = readFileSync(resolve(root, 'research/raw/ecb-eur-reference-rates-2025-09-25-to-2026-09-24.csv'), 'utf8');
const lines = csv.trim().split('\n');
const header = lines[0].split(',');
const iCur = header.indexOf('CURRENCY'), iDate = header.indexOf('TIME_PERIOD'), iVal = header.indexOf('OBS_VALUE');
const series = {};
for (const line of lines.slice(1)) {
  const cols = line.split(',');
  const cur = cols[iCur], date = cols[iDate], val = Number(cols[iVal]);
  if (!cur || !Number.isFinite(val)) continue;
  (series[cur] ||= []).push({ date, val });
}
const rates = {}; let first = null, last = null, n = 0;
for (const [cur, obs] of Object.entries(series)) {
  obs.sort((a, b) => a.date.localeCompare(b.date));
  rates[cur] = Number((obs.reduce((s, o) => s + o.val, 0) / obs.length).toFixed(4));
  first = obs[0].date; last = obs[obs.length - 1].date; n = obs.length;
}
rates.EUR = 1;
const out = `// GENERATED by scripts/build-fx.mjs from research/raw/ecb-eur-reference-rates-*.csv — do not edit by hand.
// Average of the ECB's daily euro foreign exchange reference rates over the last
// twelve months, expressed as units of each currency per 1 EUR. Used only when
// the reader turns on "Convert prices to €"; every price is also shown in its
// own currency.

export const FX = {
  base: 'EUR',
  method: 'Arithmetic mean of ECB daily reference rates',
  from: '${first}',
  to: '${last}',
  observations: ${n},
  rates: ${JSON.stringify(rates, null, 2).replace(/\n/g, '\n  ')},
};

/** Convert an amount in \`currency\` to euros at the average rate (or a custom USD rate). */
export function toEUR(amount, currency, usdPerEur = FX.rates.USD) {
  if (amount == null) return null;
  if (currency === 'EUR') return amount;
  const rate = currency === 'USD' ? usdPerEur : FX.rates[currency];
  return rate ? amount / rate : null;
}

export function fmtRate(currency) {
  const r = FX.rates[currency];
  return r >= 100 ? r.toFixed(0) : r.toFixed(2);
}
`;
writeFileSync(resolve(root, 'src/data/fx.js'), out);
console.log('fx.js written:', rates, `${first} → ${last}, ${n} obs`);
