// Generates the src/data modules the site loads from the CSV/JSON files in data/.
// data/ is the source of truth; never edit the generated modules by hand.
// Run: node scripts/build.mjs   (CI fails if the committed output is stale)
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const { COUNTRIES } = await import(resolve(root, 'src/data/countries.js'));
const { HARDWARE } = await import(resolve(root, 'src/data/hardware.js'));
const read = (name) => readFileSync(resolve(root, 'data', name), 'utf8');
const write = (name, text) => writeFileSync(resolve(root, 'src/data', name), text);

/** Minimal RFC 4180 CSV parser: returns an array of objects keyed by the header row. */
export function parseCsv(text) {
  const rows = []; let row = []; let field = ''; let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false; }
      else field += ch;
    } else if (ch === '"') inQuotes = true;
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\n' || ch === '\r') { if (ch === '\r' && text[i + 1] === '\n') i++; row.push(field); rows.push(row); row = []; field = ''; }
    else field += ch;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  const [header, ...body] = rows.filter((r) => r.length > 1 || (r.length === 1 && r[0] !== ''));
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ''])));
}

const EU = ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'];
const LANGS = ['bg', 'hr', 'cs', 'da', 'nl', 'en', 'et', 'fi', 'fr', 'de', 'el', 'hu', 'ga', 'it', 'lv', 'lt', 'mt', 'pl', 'pt', 'ro', 'sk', 'sl', 'es', 'sv'];
const snapshot = JSON.parse(read('snapshot.json'));
const header = (what) => `// GENERATED by scripts/build.mjs from data/ — do not edit by hand.\n// ${what}\n// Data as of ${snapshot.asOf}.\n\n`;
const json = (v) => JSON.stringify(v, null, 2);

// ---- snapshot ----
write('snapshot.js', header('Snapshot dates shared by the page, the README image and the footer.') + `export const SNAPSHOT = ${json(snapshot)};\n`);

// ---- availability ----
const avail = parseCsv(read('availability.csv'));
const AVAILABILITY = {}; const AVAILABILITY_META = {}; const UNKNOWN = {};
for (const r of avail) {
  AVAILABILITY[r.key] = EU.filter((c) => r[c] === 'Y');
  const unknown = EU.filter((c) => r[c] === '?');
  if (unknown.length) UNKNOWN[r.key] = unknown;
  AVAILABILITY_META[r.key] = { label: r.label, sources: r.sources ? r.sources.split(';') : [], page: r.page, section: r.section, basis: r.basis, note: r.note };
}
// Derived: all five regulated Watch health features together.
const healthKeys = ['watchEcg', 'watchIrregularRhythm', 'watchAfibHistory', 'watchSleepApnea', 'watchHypertension'];
AVAILABILITY.watchHealth = EU.filter((c) => healthKeys.every((k) => AVAILABILITY[k].includes(c)));
AVAILABILITY_META.watchHealth = { label: 'ECG, irregular rhythm, AFib History, sleep apnoea and hypertension notifications', sources: ['S13'], page: 'derived', section: healthKeys.join('+'), basis: 'country', note: 'Intersection of the five Watch health rows' };

const details = parseCsv(read('country-details.csv'));
const detailMap = (key, split = true) => Object.fromEntries(details.filter((d) => d.key === key).map((d) => [d.country, split ? d.value.split(';').map((s) => s.trim()).filter(Boolean) : d.value]));
const RETAIL_STORE_COUNTS = Object.fromEntries(EU.map((c) => [c, Number(detailMap('retailStores', false)[c] || 0)]));
write('availability.js', header('Per-country availability lists (EU member state codes) referenced from features.js via eu.avail, plus per-country details.') +
  `export const AVAILABILITY = ${json(AVAILABILITY)};\n\n` +
  `/** Countries where Apple publishes no data for the list (shown as "not published" rather than "no"). */\nexport const UNKNOWN = ${json(UNKNOWN)};\n\n` +
  `export const AVAILABILITY_META = ${json(AVAILABILITY_META)};\n\n` +
  `export const RETAIL_STORE_COUNTS = ${json(RETAIL_STORE_COUNTS)};\n\n` +
  `export const TRANSIT_CITIES = ${json(detailMap('transitWallet'))};\n\n` +
  `export const TAP_TO_PAY_PROVIDERS = ${json(Object.fromEntries(EU.map((c) => [c, detailMap('tapToPay')[c] || []])))};\n\n` +
  `export const DETAILED_CITY_CITIES = ${json(detailMap('mapsDetailedCity'))};\n\n` +
  `export function isAvailable(key, code) {\n  const list = AVAILABILITY[key];\n  return Array.isArray(list) ? list.includes(code) : null;\n}\n`);

// ---- language support ----
const langs = parseCsv(read('language-support.csv'));
const LANGUAGE_SUPPORT = Object.fromEntries(langs.map((r) => [r.key, LANGS.filter((l) => r[l] === 'Y')]));
const LANGUAGE_META = Object.fromEntries(langs.map((r) => [r.key, { label: r.label, sources: r.sources ? r.sources.split(';') : [], note: r.note }]));
write('language-support.js', header('Which of the 24 official EU languages each language-gated feature supports.') +
  `export const LANGUAGE_SUPPORT = ${json(LANGUAGE_SUPPORT)};\n\nexport const LANGUAGE_META = ${json(LANGUAGE_META)};\n`);

// ---- pricing ----
const prices = parseCsv(read('prices.csv'));
const vat = Object.fromEntries(parseCsv(read('vat-rates.csv')).map((r) => [r.country, Number(r.standardRate)]));
const PRICING = {};
for (const cc of [...EU, 'US']) {
  const rows = prices.filter((r) => r.country === cc);
  const plans = rows.filter((r) => r.product === 'appleOne').map((r) => ({ tier: r.tier, localName: r.localName, monthly: Number(r.monthly), storageGB: Number(r.storageGB), services: r.services.split(';').filter(Boolean) }));
  const fit = rows.find((r) => r.product === 'fitnessPlus');
  const currency = rows[0]?.currency || (cc === 'US' ? 'USD' : COUNTRIES.find((c) => c.code === cc)?.currency || null);
  // One entry per product in src/data/hardware.js that this storefront prices (tier "from", the entry configuration).
  const hardware = {};
  for (const h of HARDWARE) {
    const row = rows.find((r) => r.product === h.id);
    if (row) hardware[h.id] = { from: Number(row.monthly), currency: row.currency || currency, vatIncluded: row.vatIncluded === 'Y' ? true : row.vatIncluded === 'N' ? false : null, url: row.url || null };
  }
  PRICING[cc] = {
    currency,
    appleOne: { url: rows.find((r) => r.product === 'appleOne')?.url || null, plans },
    fitnessPlus: { available: !!fit, monthly: fit ? Number(fit.monthly) : null, yearly: fit ? Number(fit.yearly) : null, url: fit?.url || null },
    hardware,
    vatRate: cc === 'US' ? null : vat[cc],
  };
}
write('pricing.js', header('Apple One, Fitness+ and hardware prices (the products in src/data/hardware.js) as advertised on apple.com storefronts; standard VAT rates for the hardware tax comparison.') + `export const PRICING = ${json(PRICING)};\n`);

// ---- fx ----
const ecb = parseCsv(read('ecb-rates.csv'));
const series = {};
for (const r of ecb) { const v = Number(r.OBS_VALUE); if (r.CURRENCY && Number.isFinite(v)) (series[r.CURRENCY] ||= []).push({ date: r.TIME_PERIOD, val: v }); }
const rates = {}; let first = null, last = null, n = 0;
for (const [cur, obs] of Object.entries(series)) {
  obs.sort((a, b) => a.date.localeCompare(b.date));
  rates[cur] = Number((obs.reduce((s, o) => s + o.val, 0) / obs.length).toFixed(4));
  first = obs[0].date; last = obs[obs.length - 1].date; n = obs.length;
}
rates.EUR = 1;
write('fx.js', header('Average of the ECB daily euro reference rates over the window in data/ecb-rates.csv, as units of each currency per 1 EUR.') +
  `export const FX = ${json({ base: 'EUR', method: 'Arithmetic mean of ECB daily reference rates', from: first, to: last, observations: n, rates })};\n\n` +
  `/** Convert an amount in \`currency\` to euros at the average rate (or a custom USD rate). */\n` +
  `export function toEUR(amount, currency, usdPerEur = FX.rates.USD) {\n  if (amount == null) return null;\n  if (currency === 'EUR') return amount;\n  const rate = currency === 'USD' ? usdPerEur : FX.rates[currency];\n  return rate ? amount / rate : null;\n}\n\n` +
  `export function fmtRate(currency) {\n  const r = FX.rates[currency];\n  return r >= 100 ? r.toFixed(0) : r.toFixed(2);\n}\n`);

// ---- sources ----
const sources = parseCsv(read('sources.csv'));
const SOURCES = Object.fromEntries(sources.map((r) => [r.id, { pub: r.pub, title: r.title, url: r.url, date: r.date || null, ...(r.note ? { note: r.note } : {}) }]));
write('sources.js', header('Source register. IDs are cited from features.js, timeline.js and map-features.js.') +
  `export const ACCESSED = ${JSON.stringify(snapshot.accessed)};\n\nexport const SOURCES = ${json(SOURCES)};\n\n` +
  `export function sourceList(ids = []) {\n  return ids.map((id) => ({ id, ...SOURCES[id] })).filter((s) => s.url);\n}\n`);

// ---- US sales tax ----
const tax = parseCsv(read('us-sales-tax.csv'));
const avg = Number(tax.find((r) => r.code === 'AVG').combined);
const US_STATES = tax.filter((r) => r.code !== 'AVG').map((r) => ({ code: r.code, name: r.name, state: Number(r.state), local: Number(r.local), combined: Number(r.combined) }));
write('us-sales-tax.js', header(`Combined state + average local sales tax rates (Tax Foundation), as of ${snapshot.usSalesTaxAsOf}.`) +
  `export const US_SALES_TAX_SOURCE = 'X3';\n\n/** Population-weighted national average combined rate, per the same report. */\nexport const US_AVERAGE_RATE = ${avg};\n\n` +
  `export const US_STATES = ${json(US_STATES)};\n\nexport const US_STATE_BY_CODE = Object.fromEntries(US_STATES.map((s) => [s.code, s]));\n\n` +
  `/** Resolve the selection ('AVG' | 'NONE' | state code) to { rate, label }. */\n` +
  `export function salesTaxFor(selection) {\n  if (selection === 'NONE') return { rate: 0, label: 'no sales tax (list price)' };\n  const s = US_STATE_BY_CODE[selection];\n  if (s) return { rate: s.combined, label: \`\${s.name}, \${s.combined.toFixed(2)}%\` };\n  return { rate: US_AVERAGE_RATE, label: \`US average, \${US_AVERAGE_RATE.toFixed(2)}%\` };\n}\n`);

console.log(`built: ${Object.keys(AVAILABILITY).length} availability lists, ${Object.keys(LANGUAGE_SUPPORT).length} language lists, ${Object.keys(SOURCES).length} sources, ${US_STATES.length} states, FX ${first}→${last} (${n} obs)`);
